services:
  redis:
    container_name: anysub_redis
    restart: unless-stopped
    image: valkey/valkey:unstable

  worker:
    container_name: anysub_worker
    restart: unless-stopped
    build:
      context: ./app
      dockerfile: worker.gpu.Dockerfile
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/whisper_models:/app/wx_models
    env_file: .env
    environment:
      LIBRETRANSLATE_ENDPOINT: ${LT_ENDPOINT:-translate:5000}
      REDIS_HOST: ${REDIS_HOST:-redis:6379}
      WHISPER_MODELS: ${WHISPER_MODELS:-tiny,small}
      UPLOAD_DIR: ${UPLOAD_DIR:-/app/uploads}
      WHISPER_MODELS_DIR: ${WHISPER_MODELS_DIR:-/app/wx_models}
      WHISPER_THREADS: ${WHISPER_THREADS:-2}
      WHISPER_DEVICE: ${WHISPER_DEVICE:-cpu}
      WHISPER_HF_TOKEN: "hf_xxx"
    ports:
      - 8082:8000
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: anysub_database
    restart: unless-stopped
    image: mariadb:latest
    env_file: .env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: anysub
      MARIADB_USER: ${DB_USER:-anysub}
      MARIADB_PASSWORD: ${DB_PASSWORD:-anysub}
    healthcheck:
      interval: 5s
      retries: 5
      timeout: 30s
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]

  translate:
    container_name: libretranslate
    restart: unless-stopped
    image: libretranslate/libretranslate:latest
    user: "root"
    volumes:
      - ./anysub_data/libretranslate/data:/home/libretranslate/.local/share
      - ./anysub_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file: .env
    environment:
      LT_DISABLE_WEB_UI: True
      LT_UPDATE_MODELS: True
      LT_LOAD_ONLY: ${LT_LOAD_ONLY:-en,es}
    expose:
      - 5000
    healthcheck:
      test: ["CMD-SHELL", "./venv/bin/python scripts/healthcheck.py"]
      interval: 10s
      timeout: 30s
      retries: 5
