name: "\U0001FAB2 Bug report"
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - pluja
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Explain the bug, make sure to detail it.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Linux
        - MacOS
        - Windows
      default: 0
    validations:
      required: true
  - type: dropdown
    id: service
    attributes:
      label: Service
      description: To what service is your issue related?
      options:
        - Frontend
        - Backend
        - WhisperX API
        - I don't know
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I have searched for simmilar issues
          required: true
        - label: I am sure my issue is related to anysub
          required: true
        - label: I have searched for the error message on the internet
          required: true
