name: "[CPU] Docker whisperx-api"

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: whisperx-api
          file: whisperx-api/Dockerfile.cpu
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ format('{0}/whishperx-api:{1}-cpu', secrets.DOCKERHUB_USERNAME, github.event.release.tag_name) }}

      - name: Build and push Docker images as latest
        if: ${{ !github.event.release.prerelease }}
        uses: docker/build-push-action@v5
        with:
          context: transcription-api
          file: transcription-api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ format('{0}/whishper-transcription-api:cpu', secrets.DOCKERHUB_USERNAME) }}